version: '3.9'

services:
  mailer:
    container_name: mailer
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
    depends_on:
      rabbit:
        condition: service_healthy
      mongo:
        condition: service_healthy

  mongo:
    container_name: mailer-mongo
    platform: linux/amd64
    image: mongo:7.0.8
    hostname: mailer-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27027:27017"
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  rabbit:
    container_name: rabbit
    platform: linux/amd64
    image: rabbitmq:3.13.1-management-alpine
    hostname: mailer-rabbit
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5678:5672"
      - "15678:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 7s
      timeout: 5s
      retries: 4
      start_period: 10s

networks:
  default:
    name: cross-logger_default
    external: true
