// Code generated by ifacemaker; DO NOT EDIT.

package logger

// Controller describes methods, implemented by the logger package.
type Logger interface {
	Debug(msg string)
	Debugf(template string, args ...interface{})
	Info(msg string)
	Infof(template string, args ...interface{})
	Warn(msg string)
	Warnf(template string, args ...interface{})
	Error(err error)
	Errorf(template string, args ...interface{})
	Panic(msg string)
	Panicf(template string, args ...interface{})
	Fatal(msg string)
	Fatalf(template string, args ...interface{})
	Tracef(s string, i ...interface{})
	ErrorFull(error error)
}
