// Code generated by ifacemaker; DO NOT EDIT.

package consumer

// Controller describes methods, implemented by the repository package.
type Repository interface {
	// GetTemplateByName from the db, and save it into given part, if it can be found by name.
	GetTemplateByName(email *Email) error
}
