// Code generated by ifacemaker; DO NOT EDIT.

package consumer

// Controller describes methods, implemented by the usecase package.
type UseCase interface {
	// ProcessEmail marshal email to the consumer.Email struct and
	// send it by other email packages.
	//
	// All method should be done by one goroutine.
	ProcessEmail(b []byte)
}
