// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository.go

// Package mock is a generated GoMock package.
package mock

import (
	consumer "mailer/internal/consumer"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetTemplateByName mocks base method.
func (m *MockRepository) GetTemplateByName(email *consumer.Email) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateByName", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetTemplateByName indicates an expected call of GetTemplateByName.
func (mr *MockRepositoryMockRecorder) GetTemplateByName(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateByName", reflect.TypeOf((*MockRepository)(nil).GetTemplateByName), email)
}
