// Code generated by ifacemaker; DO NOT EDIT.

package guzzle_logger

// Controller describes methods, implemented by the guzzle_logger package.
type API interface {
	SendLog(level string, description string, messageType *string, msg interface{})
}
