server:
  name: "EMAIL_SENDER"

email:
  singleSender:
    host: "smtp.mail.ru"
    port: 465
    username: "kain.012@mail.ru"
    password: "ForMatvei"
    returnPath: "kain.012@mail.ru"
    name: "Kain Technologies"
    errorsTo: "kain.012@mail.ru"
  mailing:
    host: ""
    port: 0
    username: ""
    password: ""
    returnPath: ""
    name: ""
    errorsTo: ""

rabbit:
  mails:
    url: "amqp://user:password@rabbit:5678"
    queueName: "email"
  logs:
    url: "amqp://user:password@rabbit:5672"
    queueName: "log_api"

mongo:
  url: "mongodb://user:password@mongo:27027"
  dbName: "mailer"