// Code generated by ifacemaker; DO NOT EDIT.

package single_sender

import (
	"mailer/internal/consumer"
)

// Controller describes methods, implemented by the usecase package.
type UseCase interface {
	// SendEmail to the specified receivers with given body data.
	//
	// Can also get templates from mongoDB, if found.
	SendEmail(queueEmail consumer.Email) (recipients []string, err error)
}
