// Code generated by ifacemaker; DO NOT EDIT.

package sender

import (
	"mailer/pkg/mail"
)

// Sender represents the email client.
type Sender interface {
	// Send to the specified receivers with given body data.
	//
	// Can also get templates from mongoDB, if found.
	Send(receivedEmail *mail.Parsable) error
}
